Repository GSA/digitalgov.gov, pull requests merged in 2021-05, with the labels that each got.

#3845 Add spreadsheet file
  static/files/rpa-use-case-inventory-august-2020.xlsx
Labels: Content: PDFs

#3847 Create Image upload “content-images-_inbox-uswds-monthly-call-cover-image_may-png”
  data/images/uswds-monthly-call-cover-image-may.yml
  static/img/proxy/uswds-monthly-call-cover-image-may.jpeg
Labels: netlify-cms/draft

#3848 Create Event “2021/05/2021-05-05-uswds-accessibility-creating-more-inclusive-federal-websites”
  content/events/2021/05/2021-05-05-uswds-accessibility-creating-more-inclusive-federal-websites.md
Labels: Content: Events, netlify-cms/pending_publish

#3856 Create Image upload “content-images-_inbox-plainlanguage-may-event-title-card-png”
  data/images/plainlanguage-may-event-title-card.yml
  static/img/proxy/plainlanguage-may-event-title-card.jpeg
Labels: netlify-cms/pending_publish

#3855 Create Image upload “content-images-_inbox-deepfakes-and-social-media-title-card-png”
  data/images/deepfakes-and-social-media-title-card.yml
  static/img/proxy/deepfakes-and-social-media-title-card.jpeg
Labels: netlify-cms/pending_publish

#3857 Update Event “2021/04/2021-04-27-deep-fakes-and-social-media”
  content/events/2021/04/2021-04-27-deep-fakes-and-social-media.md
Labels: netlify-cms/pending_publish

#3858 Update Event “2021/04/2021-04-22-positioning-yourself-as-a-plain-language-editor”
  content/events/2021/04/2021-04-22-positioning-yourself-as-a-plain-language-editor.md
Labels: netlify-cms/pending_publish

#3860 Added videos
  content/events/2021/04/2021-04-20-social-media-spring-session-2021.md
Labels: Content: Events

#3862 Create Author “jenn-wingerberg/_index”
  content/authors/jenn-wingerberg/_index.md
Labels: Content: Authors, netlify-cms/pending_publish

#3863 add bio img
  content/authors/ginny-redish/_index.md
Labels: Content: Authors, Content: Images

#3846 Update checklist-of-requirements-for-federal-digital-services.md
  content/resources/checklist-of-requirements-for-federal-digital-services.md
  content/resources/required-web-content-and-links.md
Labels: :hand: HOLD

#3873 Update .nvmrc to use Node 14
  .nvmrc
Labels: Dev: GitHub + Federalist

#3875 Update checklist-of-requirements-for-federal-digital-services.md
  content/resources/checklist-of-requirements-for-federal-digital-services.md
Labels: Content: Resource

#3876 Update Author “wendy-wagner-smith/_index”
  content/authors/wendy-wagner-smith/_index.md
Labels: netlify-cms/pending_publish

#3879 Create Author “katherine-tyner/_index”
  content/authors/katherine-tyner/_index.md
Labels: netlify-cms/pending_publish

#3878 Create Author “brittany-sickler/_index”
  content/authors/brittany-sickler/_index.md
Labels: netlify-cms/pending_publish

#3886 Update principles-accessibility.md
  content/guides/mobile-principles/principles-accessibility.md
Labels: Content: Resource

#3889 Create Blog Post “2021/05/2021-05-21-how-to-navigate-challenges-to-successfully-a-b-test-your-emails”
  content/news/2021/05/2021-05-21-how-to-navigate-challenges-to-successfully-a-b-test-your-emails.md
Labels: Content: Blog post, netlify-cms/draft

#3890 Create Author “jonanthan-clinton/_index”
  content/authors/jonanthan-clinton/_index.md
Labels: Content: Authors, netlify-cms/draft

#3888 Create Blog Post “2021/05/2021-05-21-8-ways-community-of-practice-cop-managers-can-improve-member-engagement-on-listservs”
  content/news/2021/05/2021-05-21-8-ways-community-of-practice-cop-managers-can-improve-member-engagement-on-listservs.md
Labels: Content: Blog post, netlify-cms/draft

#3892 Create Event “2021/05/2021-05-21-challenge-and-prize-community-spotlight-chat-with-the-small-business-administration”
  content/events/2021/05/2021-05-21-challenge-and-prize-community-spotlight-chat-with-the-small-business-administration.md
Labels: netlify-cms/pending_publish

#3898 Create Author “jonathan-clinton/_index”
  content/authors/jonathan-clinton/_index.md
Labels: netlify-cms/pending_publish

#3896 Create Blog Post “2021/05/2021-05-24-3-things-you-should-know-about-the-federal-rpa-use-case-inventory”
  content/news/2021/05/2021-05-24-3-things-you-should-know-about-the-federal-rpa-use-case-inventory.md
Labels: netlify-cms/draft

#3901 Update 2021-05-24-3-things-you-should-know-about-the-federal-rpa-use-…
  content/news/2021/05/2021-05-24-3-things-you-should-know-about-the-federal-rpa-use-case-inventory.md
Labels: Content: Authors

#3899 Added video
  content/events/2021/05/2021-05-05-uswds-accessibility-creating-more-inclusive-federal-websites.md
Labels: Content: Events

#3902 Create Blog Post “2021/05/2021-05-25-accessibility-usability-for-every-ability”
  content/news/2021/05/2021-05-25-accessibility-usability-for-every-ability.md
Labels: Content: Redirects, netlify-cms/draft

#3904 PDF slides for accessibility event
  static/pdf/accessibility-tips-tricks-may-2021.pdf
Labels: Content: PDFs

#3905 Added slides
  content/events/2021/04/2021-04-30-accessible-digital-content-tips-and-tricks.md
Labels: Content: Events

#3909 Create Author “andy-welfie/_index”
  content/authors/andy-welfie/_index.md
Labels: netlify-cms/pending_publish

#3912 Create Event “2021/05/2021-05-28-plain-language-webinar-using-words-to-build-better-digital-experiences”
  content/events/2021/05/2021-05-28-plain-language-webinar-using-words-to-build-better-digital-experiences.md
Labels: netlify-cms/pending_publish
